name: date_time_picker
description: A Flutter widget to display a webview
version: 6.0.0
homepage: https://github.com/pichillilorenzo/flutter_inappwebview

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: